version: '3.8'

services:
  # postgres_db_latest:
  #   image: postgres:latest
  #   restart: unless-stopped
  #   container_name: postgres-latest
  #   environment:
  #     POSTGRES_USER: system
  #     POSTGRES_PASSWORD: postgres
  #   volumes:
  #     - ./tablespace:/u01
  #     - ./db-init-scripts:/docker-entrypoint-initdb.d
  #     - type: bind
  #       source: ./migration
  #       target: /app/migration
  #   ports:
  #     - 5432:5432  
  ora2pg:
    image: ora2pg
    restart: unless-stopped
    container_name: ora2pg
    environment:
      ORACLE_USERNAME: $ORACLE_USERNAME
      ORACLE_PASSWORD: $ORACLE_PASSWORD
      PG_USERNAME: $POSTGRES_USERNAME
      PG_PASSWORD: $POSTGRES_PASSWORD
    volumes:
        - type: bind
          source: ./migration
          target: /app/migration
    network_mode: "bridge"
    networks:
      bridge:
        ipv4_address: 10.0.0.4
  juror_postgres:
    image: gitlab-registry.clouddev.online/juror-digital/moj-juror/oracle-to-postgressql-migration/juror_mod_postgres
    restart: unless-stopped
    container_name: juror_postgres
    volumes:
      - ./migration:/app/migration
    networks:
      bridge:
        ipv4_address: 10.0.0.3
    ports:
      - 5432:5432
  juror_oracle_11g_rebase:
    image: gitlab-registry.clouddev.online/juror-digital/moj-juror/juror-digital-modernisation-infra/juror-oracle:v2
    restart: unless-stopped
    container_name: juror_oracle_11g_rebase
    networks:
      bridge:
        ipv4_address: 10.0.0.5
    ports: 
      - 1521:1521

networks:
  bridge:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24  